# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WithMusic' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WithMusic

  target 'WithMusicTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WithMusicUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'RongCloudIM/IMLib'
pod 'RongCloudIM/IMKit'
pod 'Masonry'
pod 'MJExtension'
pod 'MJRefresh'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'SDWebImage/GIF'
pod 'ZLPhotoBrowser'
end
